services:
  payretailers.api:
    image: ${DOCKER_REGISTRY-}payretailersapi
    container_name: payretailers_api
    build:
      context: .
      dockerfile: PayRetailers.Api/Dockerfile
    ports:
      - "8080:80" #http://localhost:8080/swagger/index.html
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TransactionsConnectionString=Host=db;Port=5432;Database=integrations;Username=pr;Password=pr123
      - ProviderApiEndpoints__PayBroBaseUrl=https://wiremock-api.azurewebsites.net/test-code/paybro
      - ProviderApiEndpoints__BankVolatBaseUrl=https://wiremock-api.azurewebsites.net/test-code/bankvolat
      - AccountSettings__LimitUsd=150.0
      - ASPNETCORE_URLS=http://+:80

  db:
    image: postgres:latest
    container_name: payretailers_postgres
    restart: always
    environment:
      POSTGRES_USER: pr
      POSTGRES_PASSWORD: pr123
      POSTGRES_DB: integrations
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: payretailers_portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  dbdata:
  portainer_data:
